-- ex. 2
-- branchNo -> branch Adress --> Branches(brnachNo*, branchAddress)
-- staffNo -> name, position --> Staff(staffNo*, name, position)
-- make sure hrs/week does depend on both by looking at dependency
-- brancNo, staffNo -> hoursperweek --> BranchStaff(branchNo*, StaffNo*, hoursPerWeek)
-- use the notation he wrote w/

-- ex.3
-- A) You would have to put a line and copy the data to seperate into diff. rows and 
--    columns as well for procedure maybe (proc id, proc description)
-- B) confirm if there multiple owners if true then it becomes a multi value attribute that
--    will have to be broken down 